# Generated by Django 5.2.7 on 2025-10-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Intro Video', max_length=200)),
                ('video_file', models.FileField(help_text='Upload your intro video (MP4 format)', upload_to='videos/')),
                ('is_active', models.BooleanField(default=True, help_text='Only one active video will be displayed')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Intro Video',
                'verbose_name_plural': 'Intro Videos',
            },
        ),
    ]
