# Generated by Django 5.2.7 on 2025-10-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_introvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vijaya Chandra Harsha Vardhan Battu', max_length=200)),
                ('title', models.CharField(default='Full Stack Developer & Tech Enthusiast', max_length=200)),
                ('about_me', models.TextField(default='Passionate full-stack developer with expertise in modern web technologies. I love creating innovative solutions and bringing ideas to life through code.')),
                ('frontend_skills', models.TextField(default='React, Vue.js, HTML5, CSS3, JavaScript')),
                ('backend_skills', models.TextField(default='Python, Django, Node.js, Express')),
                ('database_skills', models.TextField(default='PostgreSQL, MongoDB, MySQL')),
                ('tools_skills', models.TextField(default='Git, Docker, AWS, Linux')),
                ('portfolio_description', models.TextField(default='Check out my latest projects')),
                ('contact_description', models.TextField(default="Let's work together!")),
                ('email', models.EmailField(default='your.email@example.com', max_length=254)),
                ('linkedin', models.URLField(default='/in/yourprofile')),
                ('github', models.URLField(default='/yourusername')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
