# Generated by Django 5.2.7 on 2025-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['position', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Position for ordering (lower numbers appear first)'),
        ),
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, help_text='Upload your project video (MP4, AVI, etc.)', null=True, upload_to='projects/videos/'),
        ),
    ]
