# Generated by Django 5.2.7 on 2025-11-05 16:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introvideo',
            name='video_file',
            field=cloudinary.models.CloudinaryField(help_text='Upload your intro video (MP4 format)', max_length=255, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload your project video (MP4, AVI, etc.)', max_length=255, null=True, verbose_name='video'),
        ),
    ]
