# Generated by Django 5.2.7 on 2025-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_introvideo_video_file_and_more'),
    ]

    operations = [
    ]
